### PR TITLE
nothing(wasted yourtime)

### PR DESCRIPTION
**Pull request by JovadinoDev**
haha (THIS USED TO BE A DIFFERENT THING, BUT I AM A DUMBASS SO.. YEAH THIS IS NOTHING DON'T READ)

### CODE REVIEW

**Comment by ShadowMilky** [comment]
good tutorial, but why make a PR of the reverse engineered version of the week 7 demo

**Comment by biomseed** [comment]
this is a pull request 💀

**Comment by fnfporterhi** [comment]
why make a PR bro, just make a issue

**Comment by MemeHovy** [comment]
@JovadinoDev are you serious rn? close this shit

**Comment by ThePlank** [comment]
bruh... really? week7 source released you dumbo

**Comment by JovadinoDev** [comment]
my mistake, i'm stupid as hell.

**Comment by JovadinoDev** [comment]
The people who is calling me a dumbass, WELL I AM STOP HATIN!

**Comment by biomseed** [comment]
> The people who is calling me a dumbass, WELL I AM STOP HATIN!

why don't you close it?

**Comment by biomseed** [comment]
Why don't you close it?

**Comment by ShadowMilky** [comment]
*Press close issue button to proceed.*

**Comment by fnfporterhi** [comment]
he can’t close it 

PR’s have to be pushed

**Comment by KookerFoxYT** [comment]
> he can’t close it

yes he can

**Comment by mitaka78** [comment]
> he can’t close it
> 
> PR’s have to be pushed

It is very possible to close your own PR
image

**Comment by fnfporterhi** [comment]
not on mine

**Comment by KookerFoxYT** [comment]
> not on mine

then check again

**Pull request closed without merging**
