### PR TITLE
Fix week7

### PR DESCRIPTION
**Pull request by salumod**

### CODE REVIEW

**Comment by salumod** [comment]
Cut-off animation excluding stress

**Comment by salumod** [comment]
**Cut-off** animation excluding stress

**Comment by salumod** [comment]
Who knows what happened to my computer
I hate input method

**Comment by ACrazyTown** [comment]
You moved the cutscenes to the game assets... why? You don't even use them in code so whats the point

**Comment by salumod** [comment]
> You moved the cutscenes to the game assets... why? You don't even use them in code so whats the point

I just don't want it to collapse
But it's really useless

**Comment by salumod** [comment]
The music and picture of the song Stress are not **synchronized**?!

**Pull request closed without merging**
