### PR TITLE
[BUGFIX] Fixed Polymod and Mods Support in FlxPartialSound

### PR DESCRIPTION
**Pull request by KarimAkra**
This should be merged with the changes in [this pr on FlxPartialSound](https://github.com/FunkinCrew/FlxPartialSound/pull/2)

### CODE REVIEW

**Review by zacksgamerz — APPROVED** [review]

**Review by AppleHair — APPROVED** [review]

**Review by PurSnake — APPROVED** [review]

**Review by tposejank — APPROVED** [review]

**Review by AppleHair — APPROVED** [review]

**Comment by ninjamuffin99** [comment]
I've tested this and seems to function with base game songs normally and good! I'll give shout to @EliteMasterEric who has more brain on polymod stuff! I have a branch in our funkin-secret repo eric if u wanna take a peak at it !

**Review by AppleHair — APPROVED** [review]

**Review by AbnormalPoof — APPROVED** [review]
Tested with a mod and it seems to work !

https://github.com/FunkinCrew/Funkin/assets/86753001/d9c7fe8d-df78-47bf-a62b-de09d194d546

**Review by tposejank — APPROVED** [review]

**Comment by EliteMasterEric** [comment]
This wasn't working for me, and I struggled to debug it until I realized I was on a ZIP mod and apparently Polymod wasn't implementing the override for loadBytes correctly.

**Comment by tposejank** [comment]
Silly Eric

**Comment by KarimAkra** [comment]
> This wasn't working for me, and I struggled to debug it until I realized I was on a ZIP mod and apparently Polymod wasn't implementing the override for loadBytes correctly.

figured out the issue

`Assets.loadBytes` dosen't use the assets library tree but FileSystem for some reason..?

i'll get it fixed soon using `Assets.getBytes` and `ThreadPool`

**Comment by KarimAkra** [comment]
> This wasn't working for me, and I struggled to debug it until I realized I was on a ZIP mod and apparently Polymod wasn't implementing the override for loadBytes correctly.

I've just pushed a new commit to the pr on the FlxPartialSound repo that fixes this

Here's a little video of it working on base, folder mods and zip mods songs

https://github.com/FunkinCrew/Funkin/assets/144803230/1ca69822-b4fa-4043-8518-d9ce4dffdb9f

**Review by EliteMasterEric — APPROVED** [review]

**Review by PurSnake — APPROVED** [review]

**Pull request merged**
