### PR TITLE
Enable code completion

### PR DESCRIPTION
**Pull request by polybiusproxy**
A recent change in Lime caused a "Project.xml" change.
Now, code completion is only possible if the added line is there. However, it isn't on this repository.

Also all HaxeFlixel projects made after that change, will automatically have this.

### CODE REVIEW

**Review by CommandGenius — CHANGES_REQUESTED** [review]
The code is outdated, 1.0.2 should be changed to 1.0.3

**Comment by polybiusproxy** [comment]
> The code is outdated, 1.0.2 should be changed to 1.0.3

done!

**Comment by FurryColtin** [comment]
https://github.com/FurryColtin/FNF-Psych-Engine-Optinal-Features

**Comment by fireredfan7** [comment]
@FurryColtin https://youtu.be/VaLbhjekRy8

**Pull request closed without merging**
