### PR TITLE
[BUGFIXES] Cool fixes to Character Select

### LINKED ISSUE #3201: Bug Report: The character in the character select menu doesn't update properly
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

When entering the character select menu and moving to the left to select pico. the character doesn't update leaving you like this
image

you have to move to boyfriend again, and then pico so it updates properly and shows pico

ALSO NOT SURE IF IT'S A BUG but when you're playing as pico and go to character select screen the cursor will be on boyfriend and not pico (the character you're currently playing as) it kinda bothers me

### Steps to reproduce (or crash logs, errors, etc.)

_No response_

### LINKED ISSUE #3220: Bug Report: Boyfriend Dupping in Character Select and +
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

So, I don't know **why**, but when I switched characters, BF got duplicated into two. Another thing I noticed is that, for some reason, Pico is selected there even though I'm seeing BF and not Pico. 

Here is the screenshot:

image

### Steps to reproduce (or crash logs, errors, etc.)

_No response_

### LINKED ISSUE #3302: Bug Report: spamming inputs in character selection screen can make sprites not appear
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0 (Playable pico Update)

### Context (Provide images, videos, etc.)

If you spam the left and right arrow continuously in the character selection section you can cause characters to get mixed up or simply not appear sometimes.

https://github.com/user-attachments/assets/e3513d6d-b8b2-4ba0-9cd2-e13f7a3fb223

### Steps to reproduce (or crash logs, errors, etc.)

just spam

### LINKED ISSUE #3365: Bug Report: Visual bug of boyfriend persisting while hovering over a different character in character select (Plus a weird thing where boyfriend does the entry animation during the character select cutscene twice)
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Web)

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

If you go into character select, you'll notice that boyfriend actually does his intro animation twice, once at the start and again after a second or so. This is already a visual bug, but if you change characters before this second intro, your cursor will switch slots but it will stay on boyfriend visually, and another copy of his sprite will get layered behind him for some reason. Here's a video:

https://github.com/user-attachments/assets/f0fddf59-fdc4-4e5d-8ba4-5795279fcd90

It fixes itself as soon as you scroll again after waiting a sec, presumably waiting however long it would've been till that 2nd intro animation from bf. Small bug for sure.

### Steps to reproduce (or crash logs, errors, etc.)

1. Enter character select
2. Before bf's intro anim loops, swap characters
3. If you swapped to an unlocked one, bf will get a copy of himself under him and visually replace that character, otherwise, this will happen for one anim cycle and then it will switch to the unknown character animation on it's own

### LINKED ISSUE #3381: Bug Report: Boyfriend freeze frame spawns behind pico in Character select screen.
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Screenshot 2024-09-19 094502

### Steps to reproduce (or crash logs, errors, etc.)

Enter character select screen
Rapidly switch between boyfriend and lock icon during unlock animation
duplicate boyfriend freeze frame will spawn behind pico.

### PR DESCRIPTION
**Pull request by gamerbross**
## Does this PR close any issues? If so, link them below.
Fixes #3365, Fixes #3220 (same issue)
Maybe #3381 (not sure, it's really hard to replicate, but i bet it got fixed)
Fixes #3302 (already got fixed internally?)
Fixes #3201
Fixes #3381
## Briefly describe the issue(s) fixed.
- Players and GFs were not changing properly when spamming while having a little lag
- Showing BF's GF for some frames instead of the displayed character's GF (like Nene or whatever else)
- Confirm and Deny cursors not updating (changing the character before the normal cursor has moved completely)
- Fixes weird double BF after 1.5 seconds of entering
- Character not changing for the first 1.5 seconds of entering
- Spamming BF and locked character before pico gets unlocked, will show a bf behind pico (NOT SURE IF FIXED)

I think this menu got fixed a lot internally, but maybe not every of these 

## Include any relevant screenshots or videos.
All the videos are **BEFORE** the changes, to see after, it's better to try it yourself

https://github.com/user-attachments/assets/a826dffc-a8c7-4d49-bc36-a25cf86d58c9

_shows most issues_

---
image
_moving from locked to pico_

---

https://github.com/user-attachments/assets/e3cea820-6b0b-430b-991a-59f5d040b21b

_cursors not moving entirely_

---

https://github.com/user-attachments/assets/a9d53f52-0080-4a47-81a8-5c1c757a3834

_double bf and characters not changing_

### CODE REVIEW

**Comment by Hundrec** [comment]
Very cool fixes!
The menu will feel a lot smoother with these changes.

**Comment by EliteMasterEric** [comment]
There's already been a bunch of fixes to the menus in other PRs (which have already been marked as accepted)

I'll look into merging this after we update and you resolve any merge conflicts.

**Comment by ninjamuffin99** [comment]
holup my bad gamerbros i fucked up da rebase bro...

**Comment by gamerbross** [comment]
what do i do

**Pull request merged**
