### PR TITLE
feat(format): Fix formatting

### PR DESCRIPTION
**Pull request by VoltrexKeyva**
These two file's formatting is scuffed, Mashallah.

### CODE REVIEW

**Comment by KurtisCates** [comment]
Where is this file ever used in the code?

**Comment by VoltrexMaster** [comment]
> Where is this file ever used in the code?

https://github.com/ninjamuffin99/Funkin/blob/master/source/Snd.hx#L3

**Comment by Two-Ai** [comment]
Is Snd.hx ever used? It looks like both files were added in d1afc09 but were never used.
If neither file is going to be used, it would be cleaner to remove both files.

**Comment by VoltrexMaster** [comment]
> Is Snd.hx ever used? It looks like both files were added in [d1afc09](https://github.com/ninjamuffin99/Funkin/commit/d1afc09577ec1277d93f5db3081d7a9bc8b2baa6) but were never used.
> If neither file is going to be used, it would be cleaner to remove both files.

Seems like the [Snd.hx](https://github.com/ninjamuffin99/Funkin/blob/master/source/Snd.hx) file is not used literally anywhere at all, maybe its just a placeholder or a pre-state for an upcoming feature?

**Comment by The-SGPT** [comment]
based on the commits it was added for switch support

**Pull request closed without merging**
