### PR TITLE
[ENHANCEMENT] Disable traces for release builds

### PR DESCRIPTION
**Pull request by doggogit**
No clue why you guys aren't using this...

### CODE REVIEW

**Comment by doggogit** [comment]
For anyone curious, *no*, this does not disable traces in scripts in mod folders.

Example:
image

**Review by tposejank — APPROVED** [review]
pull request... approved!

**Comment by lemz1** [comment]
they already have a [branch](https://github.com/FunkinCrew/Funkin/tree/bugfix/no-traces-on-release) doing this.

**Comment by doggogit** [comment]
Oh, alright, closing!

**Comment by tposejank** [comment]
rip

**Comment by lemz1** [comment]
i do wonder though, why they havent merged it yet.

**Comment by doggogit** [comment]
> i do wonder though, why they havent merged it yet.

They'll do it at some point, it's fine, I didn't know about that branch

**Pull request closed without merging**
