### PR TITLE
its been 3 years

### PR DESCRIPTION
**Pull request by IdealistCat**
## Does this PR close any issues? If so, link them below.
nah

## Briefly describe the issue(s) fixed.
outdated modding markdown
just removed it

### CODE REVIEW

**Comment by sphis-Sinco** [comment]
aw man

**Comment by charlesisfeline** [comment]
> aw man

the devs gonna change the file at some point to include the link to the [modding docs](https://funkincrew.github.io/funkin-modding-docs/), no point in removing it anyways

**Comment by AbnormalPoof** [comment]
The file is already gone on both `main` and `develop`. The README now links to the modding documentation instead.

**Comment by sphis-Sinco** [comment]
oh

**Pull request closed without merging**
