### PR TITLE
[BUGFIX] When pressing chart key while charting, chart gets reset

### PR DESCRIPTION
**Pull request by gamerbross**
(Wasn't this already fixed?)

### CODE REVIEW

**Comment by nebulazorua** [comment]
this WAS fixed, but a PR of mine accidentally reverted the change
whoopsie!

**Comment by Matriculaso** [comment]
> this WAS fixed, but a PR of mine accidentally reverted the change whoopsie!

pendejo

**Review by trayfellow — APPROVED** [review]
pain

**Comment by EliteMasterEric** [comment]
> this WAS fixed, but a PR of mine accidentally reverted the change whoopsie!

Ah, that makes sense!

PR approved we will get it merged shortly.

**Pull request merged**
