### PR TITLE
Update license to LGPL v2.1

### PR DESCRIPTION
**Pull request by MarioNooo**
You should really update your license as quickly as possible. But here is my suggestion:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
use AGPL coward

**Comment by moxie-coder** [comment]
> You should really update your license as quickly as possible. But here is my suggestion:

IMG_5376

**Comment by MarioNooo** [comment]
> use AGPL coward

AGPL is  mostly used in Software as a Service applications, websites or other online services. This is just a game :/

**Comment by MarioNooo** [comment]
You know what? LGPL is better

**Comment by JohnFulpWillard** [comment]
> > use AGPL coward
> 
> 
> 
> AGPL is  mostly used in Software as a Service applications, websites or other online services. This is just a game :/

Since the game is on newgrounds it still works

**Pull request closed without merging**
