### PR TITLE
README changes

### PR DESCRIPTION
**Pull request by AbnormalPoof**
1. Fix formatting error in lines 4-10
2. Made line 12 bigger to emphasize it
3. Removed flixel-addons git (the transition bug was fixed lmao)
Removed flixel-addons, flixel-tools, and flixel since they are already installable via the haxeflixel link + added `haxelib install`
5. Compiling works on the latest haxe version, so 4.1.5 is no longer required
6. Added alternative method in APIStuff section
7. Added disclaimer in compiling section stating that the debug flag is optional

There's more changes but you get the idea.

also changed the haxelib git polymod to haxelib install since polymod was recently added to haxelib

### CODE REVIEW

**Comment by DotWith** [comment]
For line 5, etc

**I ADDED A SPACE BETWEEN THE ] ( SO YOU CAN VISUALIZE IT**
**REMOVE IT PLEASE**

[Play the Ludum Dare prototype] (https://ninja-muffin24.itch.io/friday-night-funkin)

[Play on Newgrounds] (https://www.newgrounds.com/portal/view/770371) or [Support the project] (https://ninja-muffin24.itch.io/funkin)

**Comment by AbnormalPoof** [comment]
@DotWith hows that?

**Comment by DotWith** [comment]
> @DotWith hows that?

Yea great.

Put this pls 

At the moment, you can optionally fix the debug screen.
- Run `haxelib git openfl https://github.com/openfl/openfl` in the terminal/command-prompt.

**Comment by AbnormalPoof** [comment]
What’s wrong with the debug screen?

**Comment by DotWith** [comment]
> What’s wrong with the debug screen?

You know that issue where the numbers are fuckie.

**Comment by AbnormalPoof** [comment]
...Huh?
Screenshot?

**Comment by DotWith** [comment]
> ...Huh?
> 
> Screenshot?

On phone. They might of fixed it already

**Comment by AbnormalPoof** [comment]
macOS needs Xcode to build so I added it to the readme

**Pull request closed without merging**
