### PR TITLE
[BUGFIX] Player's left notes being selected when they shouldn't

### LINKED ISSUE #2657: Bug Report: Player's left arrows are always selected along with Opponent's left arrows
## Operating System

- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the game are you using?
0.3.3 (still present in 0.4.1 - itch.io Version 16)

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

1. Start any song
2. Open the chart editor
3. Scroll to any point where the player has a left arrow
4. Drag and select where the left arrow would be on the opponent's side
5. The player's left arrow will be selected

## Please describe your issue. Provide extensive detail and images if possible.

Dragging to select left arrows on the **opponent's** side will also select left arrows on the **player's** side.
However, selecting the **player's** left arrows does not select the **opponent's** left arrows.

Selecting an area within the opponent's side excluding the left arrow will not select the player's left arrow.

The opponent does not have to have arrows for this bug to occur.

Through testing, it seems that only the player's left arrows are affected by this bug. All other arrows are selected normally.

https://github.com/FunkinCrew/Funkin/assets/170126004/64d5ae1a-8363-43f3-895f-904e1bb925b7

### LINKED ISSUE #3072: Selecting the WHOLE opponent section actually selecting left arrows in your section
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

"The video is too big"
https://youtu.be/L9-i7T2AqoU

### Steps to reproduce (or crash logs, errors, etc.)

idk what this means

### PR DESCRIPTION
**Pull request by NotHyper-474**
## Does this PR close any issues? If so, link them below.
* Fixes #2657
* And fixes #3072
## Briefly describe the issue(s) fixed.
When selecting any part to the left of the chart any left note in the Player's side that is in the vertical boundary of the selection box would be mistakenly selected. This is better demonstrated in the before/after video below.
## Include any relevant screenshots or videos.

https://github.com/user-attachments/assets/8576a046-d51b-4c3c-acee-892ef7b9ee7d

### CODE REVIEW

**Review by JVNpixels — APPROVED** [review]

**Review by Cartridge-Man — APPROVED** [review]
Thank god for this

**Comment by Hundrec** [comment]
An amazingly simple fix!

**Review by Hundrec — APPROVED** [review]

**Comment by NotHyper-474** [comment]
Just found a fix for this too. I don't like how it needs an additional else if tho

https://github.com/user-attachments/assets/fb5c6ddb-ef06-4bbf-b609-ba1f5eddf511

**Comment by Hundrec** [comment]
Perhaps selecting events by highlighting any region on the right should be a quality of life feature! As it stands, it's a little difficult to select only a subset of events without accidentally picking up the player's right arrows as well.

**Comment by NotHyper-474** [comment]
> Perhaps selecting events by highlighting any region on the right should be a quality of life feature! As it stands, it's a little difficult to select only a subset of events without accidentally picking up the player's right arrows as well.

Makes sense, I guess I'll only keep the fix for the left part.

**Review by anysad — APPROVED** [review]

**Review by AbnormalPoof — APPROVED** [review]

**Review by AppleHair — APPROVED** [review]

**Comment by Hundrec** [comment]
Finally in 0.5.1, woo!

**Pull request merged**
