### PR TITLE
[ENHANCEMENT/BUGFIX] Bopper auto speed check + BPM Change song event type

### PR DESCRIPTION
**Pull request by MidyGamy**
This fixes the bopper desyncing from each other, imitating the
`if(curBeat % 2 == 0)
dad.dance();`
from the 0.3.X of the game

### CODE REVIEW

**Review by PurSnake — APPROVED** [review]

**Comment by MidyGamy** [comment]
For the moment, I have to continue it...
It crashes with Week 7 and Weekend 1

**Comment by MidyGamy** [comment]
submodule are pain

**Comment by MidyGamy** [comment]
Now should work correctly

**Comment by MidyGamy** [comment]
Yeah, I just made a branch combining my 2 pull requests... I never thought that would work so well.

**Comment by MidyGamy** [comment]
So yeah, 2 bug fixes in one:
- the fact it plays too fast the idle twice (forced) after a sing pose
- sometimes the idle plays on odd beats instead of even ones
And it should find the optimal beat to dance on to be consistent if the idle last more than 2 beats

**Comment by MidyGamy** [comment]
You should notice it here:
https://www.youtube.com/watch?v=o2e4R2bUNPk

**Pull request closed without merging**
