### PR TITLE
Add a border Style instead of a variable

### PR DESCRIPTION
**Pull request by Cheemsandfriends**
This adds a border Style that it's basically the same and you don't need to add a FlxText variable to make a border effect to the typed text one

### CODE REVIEW

**Comment by polybiusproxy** [comment]
breakin news: local man fixes shitty code

**Review by AbnormalPoof — APPROVED** [review]
Actually fixing shitty code? Omg!!!!!!

**Comment by DotWith** [comment]
I thought this could do this. Now make it so it doesn't change the text color on update

**Comment by DotWith** [comment]
`swagDialogue.shadowOffset.set(2, 2);`
oh yea do this because the shadow text has this offset

**Review by NotHyper-474 — APPROVED** [review]

**Review by DotWith — APPROVED** [review]
Yay optimizations

**Pull request closed without merging**
