### PR TITLE
Add: Middlescroll and ghost tapping

### PR DESCRIPTION
**Pull request by TheBearodactyl**

### CODE REVIEW

**Comment by Noobz4Life** [comment]
AFAIK they don't wanna add ghost tapping as an option

**Comment by TheBearodactyl** [comment]
> AFAIK they don't wanna add ghost tapping as an option

:(

**Comment by TheBearodactyl** [comment]
finally, the title is FIXED

**Comment by TheBearodactyl** [comment]
i added it back along with middlescroll. if y'all really dont want ghost tapping (even as an option that's disabled by default), then at least i still made a decent contribution to one of my favorite games :)

**Comment by TheBearodactyl** [comment]
> dude thats for like a custom engine not a pr, like, the devs said not to add either of these options 

when did they ever say anything about middlescroll...?

**Comment by Hundrec** [comment]
> > dude thats for like a custom engine not a pr, like, the devs said not to add either of these options 
> 
> when did they ever say anything about middlescroll...?

I was digging through the 0.3.3 source code one time and found a comment above the strumline code for Blazin' 

It said something like "This is only a gimmick we're never adding this to the game lol!"

**Comment by TheBearodactyl** [comment]
> > > dude thats for like a custom engine not a pr, like, the devs said not to add either of these options 
> > 
> > when did they ever say anything about middlescroll...?
> 
> I was digging through the 0.3.3 source code one time and found a comment above the strumline code for Blazin' 
> 
> It said something like "This is only a gimmick we're never adding this to the game lol!"

awww :(

**Pull request closed without merging**
