### PR TITLE
Fix compilation on Linux

### PR DESCRIPTION
**Pull request by Stilic**
Some fixes for compilation on Linux.

### CODE REVIEW

**Comment by AbnormalPoof** [comment]
Wouldn't this inadvertently break ARM64 macOS compilation? The commit hash the PR changes to is really old.

**Comment by NotHyper-474** [comment]
I personally use Debian 12 and had no issues building to Linux with that branch (except for a missing lime.ndll error that was easily solved by `lime rebuild cpp -64 -release -nocffi -clean`)

**Comment by Stilic** [comment]
> Wouldn't this inadvertently break ARM64 macOS compilation? The commit hash the PR uses is really old. (It's from the `develop2` branch instead of `dev-funkin-arm64`!)
> 
> If something broke in one of the newer commits, I recommend pinpointing the issue and then submitting a fix on FunkinCrew's lime fork directly!

Oops... I thought changing the version wouldn't bring other issues...

**Comment by Stilic** [comment]
> I personally use Debian 12 and had no issues building to Linux with that branch (except for a missing lime.ndll error that was easily solved by `lime rebuild cpp -64 -release -nocffi -clean`)
> 
> Also according to [openfl/lime@d5b3294](https://github.com/openfl/lime/commit/d5b3294b20847d65fee5b9e97260b30caa6c4d47) the newer HxCpp is required for Mac ARM64 compilation (this seems to be only for NDlls tho?)

It was complaining about missing dynamic librairies because their structure got changed in the neweet versions I think.
I may look into fixing this issue at the level of Lime itself.

**Comment by Stilic** [comment]
Checked the current version of hxcpp and turns out it's newer that the one that was used before (`4.3.45` < `4.3.65`).
I will re-add hxcpp in `hmm.json` with the commit hash of that release.

**Comment by NotHyper-474** [comment]
> It was complaining about missing Freetype librairies on my laptop running Arch Linux because the structure got changed in the newest versions I think (I had all my packages up-to-date).
> I got this issue fixed for pixman by symlinking to the appropriate locations but it didn't do the trick for Freetype.
> I may look into fixing this issue at the level of Lime itself.

Perhaps that can be solved by following 
[this part](https://github.com/openfl/lime/tree/develop/project#build-troubleshooting) of the troubleshooting?

**Comment by Stilic** [comment]
I've found a way to build a Lime NDLL on Linux.
Run the following commands and then you're good to go:
```sh
cd .haxelib/lime/git
git submodule init
git submodule sync
git submodule update
lime rebuild tools
```

**Comment by Stilic** [comment]
[Opened a new PR to add the missing NDLLs to the Lime fork.](https://github.com/FunkinCrew/lime/pull/7)

**Pull request closed without merging**
