### PR TITLE
Use chart inst offset for song resync + other resync fixes

### PR DESCRIPTION
**Pull request by Burgerballs**
resyncVocals() function in PlayState now makes use of instrumentalOffset.

This PR also halves the requirement for a resync, because 100ms is a big enough difference to greatly change timings in my personal opinion.

The resyncVocals() function now also resyncs the instrumental track the same way as the vocals.

Resyncing is checked every beat instead of every step.

This PR eliminates any and all resyncing issues players are plagued with, below is a before and after;

Before:

https://github.com/user-attachments/assets/7b822328-8787-425f-bdce-b942a3cc3156

After:

https://github.com/user-attachments/assets/379890b9-6d02-4738-8dac-90af3284a50f

### CODE REVIEW

**Comment by Hundrec** [comment]
This finally fixes https://github.com/FunkinCrew/Funkin/issues/2888. Yay!

**Comment by NotHyper-474** [comment]
Doesn't #2706 already do the desync fix?

**Review by Cartridge-Man — APPROVED** [review]

**Review by cyn0x8 — APPROVED** [review]

**Review by doggogit — APPROVED** [review]

**Review by VirtuGuy — APPROVED** [review]

**Comment by EliteMasterEric** [comment]
Worked well for me when I tried it, and since it works for a bunch of other reviewers I'd say it's good.

**Comment by Sword352** [comment]
Any reasons the tracks are being paused though? You can just set the sound's time and move on

**Comment by VirtuGuy** [comment]
> Any reasons the tracks are being paused though? You can just set the sound's time and move on

You can't just set the sound's time and move on without pausing as that would cause issues getting both the instrumental and vocals synced.

**Review by tposejank — APPROVED** [review]

**Review by AbnormalPoof — APPROVED** [review]

**Review by NotHyper-474 — APPROVED** [review]

**Comment by Burgerballs** [comment]
> Any reasons the tracks are being paused though? You can just set the sound's time and move on

Pausing both tracks at the same time stops the time variable from increasing while you're setting it, making it easier to resync.

**Comment by EliteMasterEric** [comment]
> Pausing both tracks at the same time stops the time variable from increasing while you're setting it, making it easier to resync, and makes it more accurate.

I was under the impression `FlxSound.time` only increases during the `update()` function.

**Comment by Burgerballs** [comment]
> > Pausing both tracks at the same time stops the time variable from increasing while you're setting it, making it easier to resync, and makes it more accurate.
> 
> I was under the impression `FlxSound.time` only increases during the `update()` function.

The time variable does *change* during the update function but it doesn't really *increase* if paused.

**Pull request merged**
