### PR TITLE
Fix some spaghetti on PlayAnimationSongEvent

### PR DESCRIPTION
**Pull request by Burgerballs**

### CODE REVIEW

**Review by trayfellow — APPROVED** [review]
Oh my god 😭

**Review by BlueColorsin — APPROVED** [review]
Oh god why was it done like that 😭

**Review by EliteMasterEric — APPROVED** [review]
I must have been really tired when I wrote this (or maybe I just forgot the syntax for multiple pattern matching lol).

sonic-boom-knuckles

**Comment by EliteMasterEric** [comment]
Turns out that you got the syntax for this wrong! It's `|` and not `||`. Did you make this change through the website?

I thought for sure that would work too but apparently not.

**Comment by Burgerballs** [comment]
> Turns out that you got the syntax for this wrong! It's `|` and not `||`. Did you make this change through the website?
> 
> I thought for sure that would work too but apparently not.

this is a big whoopsie i must explode into several tiny versions of me and run aimlessly like that super mario 3d world boss

**Pull request merged**
