### PR TITLE
[ENHANCEMENT] Custom ratings with custom note style

### PR DESCRIPTION
**Pull request by AlexGamingSW**

### CODE REVIEW

**Comment by EliteMasterEric** [comment]
This should honestly be defined BY the note style itself (so that custom note styles can apply new ratings graphics).

**Comment by AlexGamingSW** [comment]
Alright, I'll try!

**Comment by AlexGamingSW** [comment]
Goes along with this https://github.com/FunkinCrew/funkin.assets/pull/29

**Comment by AlexGamingSW** [comment]
This was added in 0.5.0

**Pull request closed without merging**
