### PR TITLE
Add FPS Option

### PR DESCRIPTION
**Pull request by lemz1**
## Additions
- fps option which goes from 60 to 360

## TODO
- [x] use implementation of #2793 (only add whats necessary)

## PREVIEW
https://github.com/FunkinCrew/Funkin/assets/87707926/f8821b71-81f6-470f-999b-2aa3bb9ebe44

### CODE REVIEW

**Comment by Bezizeja** [comment]
have it go up to 360 fps

**Comment by lemz1** [comment]
> have it go up to 360 fps

its already capped at 360

**Comment by EliteMasterEric** [comment]
Note, might conflict with #2793

**Comment by lemz1** [comment]
> Note, might conflict with #2793

This shouldnt conflict with #2793 anymore

**Comment by AbnormalPoof** [comment]
v0.5.0 has an "Unlocked Framerate" option now.

**Comment by EliteMasterEric** [comment]
Unlocked framerate is a web only thing

v0.5 has support for numeric options so adding an FPS limit option to desktop would be great

**Comment by Bezizeja** [comment]
so i got the 0.5.1 version that has this implementation if you put above 165fps game is not smooth at all and feels really weird i have 240hz monitor and it doesnt utilise it

**Comment by lemz1** [comment]
can you elaborate?

do you actually get 240 fps?maybe your pc cant reach 240fps in fnf

**Comment by Bezizeja** [comment]
oh wait nvm it is smooth everything good

**Comment by DustedDustin** [comment]
Any particular reason why the cap is set to 300 on desktop? The web version's unlocked framerate option bases it off of your monitor and can reach 360 but on the desktop version I can't fully utilize my 360hz monitor. I know there's refresh rates higher than that but 360 isn't too terribly rare especially for 1080p monitors

**Comment by EliteMasterEric** [comment]
> Any particular reason why the cap is set to 300 on desktop? The web version's unlocked framerate option bases it off of your monitor and can reach 360 but on the desktop version I can't fully utilize my 360hz monitor. I know there's refresh rates higher than that but 360 isn't too terribly rare especially for 1080p monitors

It was completely arbitrary! I forgot about 360hz monitors when choosing that value, I have no objections to raising it.

**Comment by DustedDustin** [comment]
I have a ryzen 5 5600, 16gb of ram, and a rtx 3070ti. None of which is too strong by today's standards

Running it on newgrounds i consistently reach around 360 in songs and menus with minor dips (idk how it performs on anything higher because 360 is my monitor's cap) 

Personally I definitely feel 360 should be included because it's starting to become not so uncommon on monitors especially for rhythm or fps gamers who choose 1080p. 

480 or 500 maybe but they're not really on too many monitors yet but I guess it couldn't hurt?

**Pull request merged**
