### PR TITLE
[FEATURE] Better issue and pull request templates

### PR DESCRIPTION
**Pull request by tposejank**
Basically, makes every issue and PR template look more fancy.

## Examples

- bug.yml
image

- enhancement.yml
image

Please tell me if anything is wrong! Thanks!

### CODE REVIEW

**Review by NotHyper-474 — APPROVED** [review]
Tested this on my fork, it's way better and more user friendly!

**Review by trayfellow — APPROVED** [review]

**Comment by tposejank** [comment]
Finally i fixed the merge issues!!

**Comment by ninjamuffin99** [comment]
nice these are awesome :) I think for "question" ones like compiling help we can just neglect/remove templates, and rather use the github discussions tab.

**Comment by tposejank** [comment]
> nice these are awesome :) I think for "question" ones like compiling help we can just neglect/remove templates, and rather use the github discussions tab.

Done!

**Comment by EliteMasterEric** [comment]
Hey @tposejank If you could modify this PR to resolve the existing merge conflicts, and use the new labels (apply the appropriate `type` and the `status: pending triage` label to all new issues) that would be great.

**Comment by tposejank** [comment]
> Hey @tposejank If you could modify this PR to resolve the existing merge conflicts, and use the new labels (apply the appropriate `type` and the `status: pending triage` label to all new issues) that would be great.
> 
> EDIT: A third template for crash bugs that requires uploading a log would also be great!

Alright Eric, I've noted that! I'll resolve the conflicts tomorrow because it's late. But I will add the labels.

**Comment by tposejank** [comment]
Oh well seems like I can't add labels

**Comment by tposejank** [comment]
AGHHHHHHHHHH

**Comment by tposejank** [comment]
FINALLY

**Comment by tposejank** [comment]
Alright @EliteMasterEric, please review!

I have added the `crash.yml` file, a new template which is similar to the bug one but has the steps to reproduce and a crash log area which is required. 

The issue and pr templates all have the `status: pending triage` tag to be automatically applied.

On the bug issue template, `type: minor bug` is applied.

On enhancement issue template, `type: enhancement` is applied.

On crash issue template, `type: major bug` is applied.

On the PR bug template, `type: minor bug` is applied, and on enhancement, `type: enhancement`.

Unfortunately, GitHub does not provide a way for users to choose which label works appropriately for the issue/pr, so the others will have to be added manually.

The merge conflicts have also been fixed. That seems to be because of mismatching diffs on the deleted `bug.md` file.

**Comment by tposejank** [comment]
Also yeah... PR templates kinda don't work.

**Comment by EliteMasterEric** [comment]
Thank you very much! I will review this tomorrow. It should be a big help in managing future issues.

**Comment by EliteMasterEric** [comment]
I completely forgot about this PR, LOL!

If PR templates don't work, please remove them.

Otherwise, if you look into fixing the conflicts I'll merge this @tposejank

**Comment by tposejank** [comment]
WHY ARE THERE STILL CONFLICTS 😭😭
No worries I'll fix them ASAP.

**Comment by Hundrec** [comment]
I really liked this PR and was wondering why it was stuck in limbo!

**Comment by tposejank** [comment]
> I completely forgot about this PR, LOL!
> 
> If PR templates don't work, please remove them.
> 
> Otherwise, if you look into fixing the conflicts I'll merge this @tposejank

done!! you can merge now @EliteMasterEric 

as a remark, the `bug.md` inside the PR templates was renamed to `PULL_REQUEST_TEMPLATE.md` as that IS the correct way to do PR templates

**Comment by EliteMasterEric** [comment]
👍 I don't want to keep this in limbo because it'll save me time reviewing stuff so let's just ship it and see if it works we can make tweaks later

**Comment by EliteMasterEric** [comment]
@tposejank I don't think the PR template quite works as intended, but the issue template works fantastic and that should drastically improve things going forward!

image

**Comment by tposejank** [comment]
Yeah.... I don't know why GitHub has done proper support for PR templates. It's something on their part, but important part is the "template" itself works to say the least
I sure hope it does!

**Pull request merged**
