### PR TITLE
[BUGFIX] Fix Force Animations in GameOverSubState

### PR DESCRIPTION
**Pull request by anysad**
- This simple PR aims to fix forced animations in songs (for example: Bopeebo, Spookeez, 2Hot) that broke the death animation (in case you die, or just press R).
- Before it broke not only the animation, but also the music that came along with it.
- This also has been mentioned in Issues like: #2319, #2680 and #2871 (in the [comment ](https://github.com/FunkinCrew/Funkin/issues/2871#issuecomment-2182108301)by Hundrec)

Before:

https://github.com/FunkinCrew/Funkin/assets/69017727/2908df7f-adac-4b64-a1ca-db9a08e6d175

After:

https://github.com/FunkinCrew/Funkin/assets/69017727/52d88518-f265-4ca8-ba83-651ee60826f1

### CODE REVIEW

**Comment by Hundrec** [comment]
Wow, this was surprisingly easy to fix. Thank you!

**Review by Hundrec — APPROVED** [review]

**Comment by Hundrec** [comment]
I suppose they fixed this issue internally. Do you know what they changed to fix it?

**Comment by AbnormalPoof** [comment]
> I suppose they fixed this issue internally. Do you know what they changed to fix it?

```diff
boyfriend = PlayState.instance.currentStage.getBoyfriend(true);
+ boyfriend.canPlayOtherAnims = true;
boyfriend.isDead = true;
```

**Comment by anysad** [comment]
fixed ig

**Pull request closed without merging**
