### PR TITLE
Title name text - introText for name before skipIntro is called

### PR DESCRIPTION
**Pull request by kitkatwastaken**

### CODE REVIEW

**Comment by aflacc** [comment]
I feel like there could be a whole file dedicated to the credits & intro

**Comment by prokube** [comment]
### IDEA:

```json
{
    "bpm":"102",
    "sequence":
    [
        [{"beat":0}, {"text":["%clear"]}],
        [{"beat":1}, {"text":["Cube Crew"]}],
        [{"beat":3}, {"text":["presents"]}],
        [{"beat":4}, {"text":["%clear"]}]
    ]
}
```

`%clear` clears the text on screen, and you can set the bpm of the sequence using the `bpm` tag up there. Besides that, you just paste the same module for as much text as you want.

wait a sec this a badass pr idea i might do this for kade

**Comment by ThePlank** [comment]
> ### IDEA:
> ```json
> {
>     "bpm":"102",
>     "sequence":
>     [
>         [{"beat":0}, {"text":["%clear"]}],
>         [{"beat":1}, {"text":["Cube Crew"]}],
>         [{"beat":3}, {"text":["presents"]}],
>         [{"beat":4}, {"text":["%clear"]}]
>     ]
> }
> ```
> 
> `%clear` clears the text on screen, and you can set the bpm of the sequence using the `bpm` tag up there. Besides that, you just paste the same module for as much text as you want.
> 
> wait a sec this a badass pr idea i might do this for kade

Cool! more ideas to steal for my engine!

**Comment by prokube** [comment]
> > ### IDEA:
> > ```json
> > {
> >     "bpm":"102",
> >     "sequence":
> >     [
> >         [{"beat":0}, {"text":["%clear"]}],
> >         [{"beat":1}, {"text":["Cube Crew"]}],
> >         [{"beat":3}, {"text":["presents"]}],
> >         [{"beat":4}, {"text":["%clear"]}]
> >     ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `%clear` clears the text on screen, and you can set the bpm of the sequence using the `bpm` tag up there. Besides that, you just paste the same module for as much text as you want.
> > wait a sec this a badass pr idea i might do this for kade
> 
> Cool! more ideas to steal for my engine!

feel free to lol, im putting it in mine

**Pull request closed without merging**
