### PR TITLE
Opponent arrow flash

### PR DESCRIPTION
**Pull request by ihearrodmod**
i have no idea if this is already being implemented or if this is even efficient but here it is

arrows

### CODE REVIEW

**Comment by aflacc** [comment]
YES

**Review by TentaRJ — APPROVED** [review]
Looks good!

**Comment by edgardeivis** [comment]
what does this do

**Review by hdboye — APPROVED** [review]
Yes please, this looks amazing. So much more satisfying than the regular note disappearing.

**Review by actuallyasmartname — APPROVED** [review]
ayy

**Review by PurpleButNotALight — APPROVED** [review]
yes.

**Comment by AbnormalPoof** [comment]
This could be an option idk

**Pull request closed without merging**
