### PR TITLE
Fix windows compilation issue

### PR DESCRIPTION
**Pull request by Pietrodjaowjao**

### CODE REVIEW

**Comment by Raltyro** [comment]
Windows compile fine already though, i was thinking of instead of making A-Bot Visuals ftt only works for web, why not somehow making windows work too somehow

**Comment by Pietrodjaowjao** [comment]
makes sense

**Comment by Pietrodjaowjao** [comment]
i will try to do this instead and rename the pr lol

**Comment by Raltyro** [comment]
Welp since this uses funkin.vis which is a seperate repo, i think you should close this pr instead, also the ftt work seem to be hard though to make it work for native

**Comment by EliteMasterEric** [comment]
The game already builds on desktop without this, this doesn't fix anything.

**Pull request closed without merging**
