### PR TITLE
custom capsule colors

### PR DESCRIPTION
**Pull request by 7oltan**
this pr makes you change the color of the capsule through the freeplay style json of your playable character instead of making a whole new sprite sheet

you can set the bg color, the deselected bg color and the glow color

WARNING
this fucks up the rank animation, i havent tested it but i commented out some code for the trails + impact + shader?? 
another thing, picos colors are a lil weird bc there isnt an fla for picos freeplay capsule so i cant copy the exact color

i might work on this later but im done with it for now

### CODE REVIEW

**Review by charlesisfeline — APPROVED** [review]

**Comment by Hundrec** [comment]
Cool idea! Can you provide some example screenshots?

**Comment by JVNpixels** [comment]
Couldn’t you already do this? Or is this a new system that is revamped?

**Comment by trayfellow** [comment]
> Couldn’t you already do this? Or is this a new system that is revamped?

image

Im pretty sure you were able to do this already, completely lets you change the spritesheet too

**Comment by 7oltan** [comment]
> Couldn’t you already do this? Or is this a new system that is revamped?

Before this pr you can only change the color of the capsule screen by changing the whole sprite sheet, after the pr you can customize the color(s) of the capsule screen using json data instead of making multiple spritesheets that bloat the game

**Comment by 7oltan** [comment]
> Cool idea! Can you provide some example screenshots?

I’ll do that later today!

**Comment by JVNpixels** [comment]
I was able to change the capsule color with .json I swear but maybe it was broken and didn’t work. Still respect this PR!

**Comment by 7oltan** [comment]
> I was able to change the capsule color with .json I swear but maybe it was broken and didn’t work. Still respect this PR!

I don’t think that’s possible as of now…. There is a variable in the json to change the text colors you maybe confused the two

**Comment by 7oltan** [comment]
i kinda forgor about this again, sorrryyu

**Comment by 7oltan** [comment]
errr i dont want to do this no more, if anyone want it TAKE ITTTT

**Comment by AbnormalPoof** [comment]
If you aren't working/don't want to work on a PR anymore, it's better to just close it instead of leaving it open.

**Pull request closed without merging**
