### PR TITLE
[docs] Add missing changes and links to Changelog

### LINKED ISSUE #3676: Enhancement: Changelog Fixing
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

Basically just add the new contributors section to 0.5.0 and 0.5.1 since it feels weird and I wanna see who contributed, and the format doesn’t really fit with the other changelog sections.

### PR DESCRIPTION
**Pull request by Hundrec**
_(fixes #3676)_
Oh whoops, was doing this at the same time as Eric

I've made a bunch of changes to the changelog that I think are necessary, so I'll be adding a commit to resolve merge conflicts with Eric's commit

All resolved!

## Changes
- **[NEW]** Add and polish changes for 0.5.3
- Add a few changes that are missing due to closed PRs
- Add PR links for new contributors in 0.5.2
- Add new contributors sections for 0.5.1, 0.5.0, 0.4.1, 0.4.0, and 0.3.3
- Add links to pull requests for all changes that came from a PR for all versions back to 0.3.3
- Tweak the spellings of some contributors' names to match their usernames on GitHub
- Various spelling and grammar fixes after 0.3.0
- Remove duplicate entries
- Fix a broken link in 0.4.1

And most of all...
- Change the 'h' in "2hot" to lowercase (and fixed M.I.L.F and DadBattle)

### CODE REVIEW

**Review by JVNpixels — APPROVED** [review]
Wonderful, perfect!

**Comment by EliteMasterEric** [comment]
This is great! I would like to see if this can get rebase/squashed to be compatible with the current `main` branch.

**Comment by JVNpixels** [comment]
whoops, forgot to add a period, thank you for adding it Hundrec!

**Review by EliteMasterEric — APPROVED** [review]

**Comment by Hundrec** [comment]
I've included the latest changes from 0.5.3 and fixed up a few things:
* Removed a duplicate entry
* Reordered an enum fix for better readability
* Finished the final sentence (with what I think you meant to write)

I want to squash this into one commit, but I'm not sure how to. Can you guys do it?

**Comment by EliteMasterEric** [comment]
Let's see if this works

**Comment by Keoiki** [comment]
Well now the 0.5.3 changelog is inconsistent between Main and Develop branches since the final entry is completely different

**Comment by Hundrec** [comment]
Whoops! Didn't realize Eric finished his sentence in develop.
I'll let Eric handle the conflict.

**Pull request merged**
