### PR TITLE
check if response result is actually there

### LINKED ISSUE #410: Bug Report: Freeplay menu crashes when no API Key is present
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

_I am playing on Windows (`x86_64`)._

## What version of the game are you using? Look in the bottom left corner of the main menu.

_0.2.7 - latest commit at time of writing (3758171)_

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

_Yes. Compile the game with blank API keys, and go to the freeplay menu._

## Please describe your issue. Provide extensive detail and images if possible.

_Title says all. As of the merging of #362 custom compiles will crash if a blank API key is supplied. I suspect this is because NGIO tries to call ``Fresh`` on the freeplay menu, but cant due to the lack of an API Key._

### PR DESCRIPTION
**Pull request by Jan200101**
follow up on #362
fixes #410
the thing that was causing problems with an invalid API key was response.result being null since the response Newgrounds gives just tells us that we have an invalid app id.

Since we now actually create NG.core we will always get a console message when anything with NG.core is done that requires the api.

### CODE REVIEW

**Review by ActualMandM — APPROVED** [review]

**Comment by SixBeeps** [comment]
Works on my machine 👍

**Comment by aflacc** [comment]
wait is this like a failsafe

**Comment by Steviegt6** [comment]
> 
> 
> wait is this like a failsafe

Yeah? It just ensures that nothing should happen if the response returns a `null` result. The original failsafe check was just checking if `api`'s `Length` was `0`, which clearly didn't work.

**Comment by Jan200101** [comment]
The original implementation was rather simplistic with and never actually created a Newgrounds object when the api key was empty
this works in theory but every time you change song in Freeplay it makes Newgrounds calls, which fall on deaf ears because were never init'd it

this patch changes it around to see if we actually get a response
Invalid API keys (such as an empty one) will cause the library to output a warning and null any response that was expected to have something
accessing a member of null isn't possible so we crash

**Comment by Michael82548** [comment]
Sooo can we merge? Right now freeplay is not playable

**Comment by Michael82548** [comment]
#1232

**Comment by jamestmartin** [comment]
This also fixes #1001. Despite the branch being super old there are still no merge conflicts. Merging this is a no-brainer.

Pinging @ninjamuffin99 because this PR seems like it's been overlooked.

**Comment by VMGuy23** [comment]
Yeah @ninjamuffin99 needs to merge

**Comment by Steviegt6** [comment]
Very well could have already been fixed on a private branch. You guys are forgetting that the public GitHub repository isn't up-to-date.

**Comment by Michael82548** [comment]
> Very well could have already been fixed on a private branch. You guys are forgetting that the public GitHub repository isn't up-to-date.

Isn't this the only way we can actually see changes being made before release though?

**Comment by aflacc** [comment]
yall okay with me putting this on projectfnf?

**Comment by Jan200101** [comment]
Feel free to do whatever with this
on that note

Yes it is likely that development is continuing in a private repo considering the Kickstarted

**Comment by AbnormalPoof** [comment]
this should be merged

**Pull request closed without merging**
