### PR TITLE
GitHub Actions Test Pull Request + Documentation Fixes

### PR DESCRIPTION
**Pull request by Hundrec**
The latest Pull Request was actually labeled by GitHub Actions, so this PR tests it again.

I actually noticed a few things that needed changing, so I've made valid changes that Eric should take a look at:
- Noted an unfinished sentence in the Build Flags section of `COMPILING.md` (fixes https://github.com/FunkinCrew/Funkin/issues/3478)
- Renamed `troubleshooting.md` to `TROUBLESHOOTING.md` to fix a broken link in the Compiling Guide
- Miscellaneous grammatical fixes

### CODE REVIEW

**Comment by AbnormalPoof** [comment]
I wonder why there's a separate label for documentation instead of just using the `type: documentation` label.
Screenshot 2024-10-04 at 11 30 19 PM

**Comment by Hundrec** [comment]
Good point!
I was going to change the label until I saw your edit
I'll just let Eric handle the best way to label things.

**Comment by Hundrec** [comment]
Just realized that the size labels take the sum of additions and deletions.
5 line changes = 10 changes = `medium`
Noting this here so Eric can decide what a small/medium PR really is.

**Comment by LukerUpgradez** [comment]
I noticed the all-caps issue with the troubleshooting link a couple days ago but never got around to trying to fix it. Thanks for taking care of that!

**Comment by EliteMasterEric** [comment]
> Maybe to separate PRs that edit the source code and PRs that edit the `.md` files? I'm not really sure.

`documentation` labels those PRs that edit `.md` files and `haxe` labels those PRs that edit `.hx` files. I think this is fine as is because some pull request modify both.

**Review by EliteMasterEric — APPROVED** [review]

**Pull request merged**
