### PR TITLE
[ENHANCEMENT] Link the official modding documentation in repository README

### PR DESCRIPTION
**Pull request by Cartridge-Man**
## Does this PR close any issues? If so, link them below.

#3080 

## Briefly describe the issue(s) fixed.

Just adds a link to the book created by the official Funkin’ Crew to the repository’s README.

### CODE REVIEW

**Comment by biomseed** [comment]
You did the wrong thing. I was talking about the mods folder readme. There is a readme in the mods folder. This is for the REPOSITORY. Do not do this.

**Comment by biomseed** [comment]
> I feel like [Modding.md](https://github.com/FunkinCrew/Funkin/blob/main/Modding.md) could also be updated

That is a really old file so I think they should get rid of it instead. The README in the mods folder is a better replacement and it is in all release builds

**Comment by NotHyper-474** [comment]
> Replying to https://github.com/FunkinCrew/Funkin/pull/3082#issuecomment-2266155655

You mean like the [introMod/README.md](https://github.com/FunkinCrew/Funkin/blob/main/example_mods/introMod/README.md) file or the "do NOT readme.txt"? If the former these example mods don't even get copied to release builds due to a problem.

https://github.com/FunkinCrew/Funkin/blob/9b483de1da9c1b72b02ec30f4d13923470cf32b9/Project.xml#L90-L97

**Comment by biomseed** [comment]
> You mean like the [introMod/README.md](https://github.com/FunkinCrew/Funkin/blob/main/example_mods/introMod/README.md) file or the "do NOT readme.txt"? If the former these example mods don't even get copied to release builds due to a problem.
> 
> https://github.com/FunkinCrew/Funkin/blob/9b483de1da9c1b72b02ec30f4d13923470cf32b9/Project.xml#L90-L97

The mods folder has a readme. Look inside it in a release build and you will see. I know what I'm talking about.

**Comment by NotHyper-474** [comment]
> Replying to https://github.com/FunkinCrew/Funkin/pull/3082#issuecomment-2266173574

Couldn't find anything, and this is a fresh download.
image

**Comment by biomseed** [comment]
> 
> Couldn't find anything, and this is a fresh download. image

Oh my god I'm so sorry, I thought the mods folder had a readme but it was just mandela effect or something, there was one with codename engine and for some reason I thought there was one in the mods folder in the base game

**Comment by NotHyper-474** [comment]
> Oh my god I'm so sorry, I thought the mods folder had a readme but it was just mandela effect or something, there was one with codename engine and for some reason I thought there was one in the mods folder in the base game

It's alright, happens to the best of us lol.

**Comment by Cartridge-Man** [comment]
> You did the wrong thing. I was talking about the mods folder readme. There is a readme in the mods folder. This is for the REPOSITORY. Do not do this. This should not close my issue. I'm pretty sure the mods folder just shows up on release builds, so if the mods folder's README is copied from something in this repo, you should edit that instead. If not, this should not be merged because then it will close my issue.
> If you decide to update this if my suggestion is possible, use the dev branch instead just in case any updates release. That'll remove any merge conflicts if this isn't merged until a hotfix.
> EDIT: I was confused and there is no readme in the mods folder. They should add one though. I changed things in my issue as appropriate and someone said that this shouldn't automatically close my issue. You should remove the section though as I still stand by the mods folder thing in the issue.

I think I just experienced brain damage, but thanks for the support! (This is a joke, I’m not actually trying to be mean, I mean, I might be, but idk!)

**Comment by biomseed** [comment]
> I think I just experienced brain damage, but thanks for the support! (This is a joke, I’m not actually trying to be mean, I mean, I might be, but idk!)
I don't think you're joking. That was a LONG LONG stream of text with a lot of edits made

**Review by biomseed — APPROVED** [review]
I think this one is good actually

**Comment by ninjamuffin99** [comment]
i busted up the git rebase derp derp im still learning... 

but I did get this merged! thank you!

**Pull request closed without merging**
