### PR TITLE
[FEATURE] Scroll Speed Event

### PR DESCRIPTION
**Pull request by Burgerballs**
https://github.com/FunkinCrew/Funkin/assets/107233412/d0626047-9dad-4ac7-8e01-3ced7b20f69f

What this PR does is implement a new event that sets the current scroll speed. As well as a public ``scrollSpeed`` variable in Strumline. Without adding any sustain-related rendering issues.

image

This PR also adds a ``parentStrumline`` variable to SustainTrail, and a way for it to redraw once the scroll speed changes.

https://github.com/FunkinCrew/Funkin/assets/107233412/8b5fe4d9-e78b-4000-afc0-7cb744b5d234

The event can also affect either strumline, an example of this is the video above!

image
This event can also set the base scroll directly instead of acting as a multiplier (disabled by default)!

Setting the value to 1 with Absolute disabled will set the speed to the default. (important)

PS; i **ACTUALLY** tested it this time

### CODE REVIEW

**Comment by Burgerballs** [comment]
Converted to draft in order to add an extra cool feature. Changing the speed of a single strumline!

**Comment by amyspark-ng** [comment]
shouldn't it be just to set the new scroll speed? i think that'd be nicer...

**Comment by Burgerballs** [comment]
> shouldn't it be just to set the new scroll speed? i think that'd be nicer...

Noted, making changes right now

**Comment by Burgerballs** [comment]
I have now undrafted it lol

**Comment by amyspark-ng** [comment]
This is pretty awesome

**Comment by Burgerballs** [comment]
is there anything else that should be added to this or is it all good

**Comment by ninjamuffin99** [comment]
this is pretty awesome ! Gonna ping @EliteMasterEric for his thoughts on how it's implemented code wise, but def something we can use in places ! Thanks!

**Comment by Burgerballs** [comment]
> this is pretty awesome ! Gonna ping @EliteMasterEric for his thoughts on how it's implemented code wise, but def something we can use in places ! Thanks!

Thank you!

**Comment by EliteMasterEric** [comment]
Once I can check the code more thoroughly I can give more feedback, but I like this in general.

Have you tried seeing how it reacts visually when changing scroll speed while notes are visible? The tween should keep it from glitching but I'm curious how it looks.

Also, 1.0 should reset to the base scroll speed, not 0.0.

Maybe there could also be an absolute checkbox (unchecked by default) that sets the value rather than applying a multiplier?

**Comment by Burgerballs** [comment]
> Once I can check the code more thoroughly I can give more feedback, but I like this in general.
> 
> Have you tried seeing how it reacts visually when changing scroll speed while notes are visible? The tween should keep it from glitching but I'm curious how it looks.
> 
> Also, 1.0 should reset to the base scroll speed, not 0.0.
> 
> Maybe there could also be an absolute checkbox (unchecked by default) that sets the value rather than applying a multiplier?

Sounds like good ideas, i'll try to put them in

**Comment by Burgerballs** [comment]
don e

**Comment by Burgerballs** [comment]
the sustains were broke but now they not :D

**Comment by Burgerballs** [comment]
@EliteMasterEric once ur able to check the code could you make sure to tell me if theres anything wrong

**Comment by EliteMasterEric** [comment]
I've been busy with other tasks lately, I will definitely look into reviewing it soon-ish!

If it looks good and doesn't have any problematic bugs, I will try to merge it to have it available for the next content update.

**Comment by Burgerballs** [comment]
> I've been busy with other tasks lately, I will definitely look into reviewing it soon-ish!
> 
> If it looks good and doesn't have any problematic bugs, I will try to merge it to have it available for the next content update.

Alr!

**Comment by EliteMasterEric** [comment]
Finally got around to testing this and it worked great!

**Pull request merged**
