### PR TITLE
Update Main.hx

### PR DESCRIPTION
**Pull request by tohar777**
added simple About in Main.hx!!

### CODE REVIEW

**Comment by moxie-coder** [comment]
https://github.com/FunkinCrew/Funkin/assets/124418090/611683bd-12bd-4d67-b199-2bd1f8f87c34

The fuck is this shit supposed to be

**Comment by CharlesCatYT** [comment]
this is more pointless than what i've seen in the psych engine prs, the hell dude?

**Comment by NotHyper-474** [comment]
Who let them cook

**Comment by richTrash21** [comment]
ezgif-6-4a33625b71

**Comment by tposejank** [comment]
remove yourself

**Comment by CharlesCatYT** [comment]
also this is the same guy who did that one pr that is just ``hi.txt``, and other prs in countless other repos 
image


makes it clear that-

# we aint safe from the fruitless pull requests.

**Comment by tohar777** [comment]
## I DON'T GIVE A F#CK

LoL  I only did it once

**Comment by MadBear422** [comment]
Please close this already

**Comment by Dxgamer7405** [comment]
good job, it will really help!!!

**Comment by Sword352** [comment]
Hey, let's calm down and kindly explain to the author that it's useless. They might have made it from heart, ya know.

This PR does nothing but adds some already known informations to the main module, and credits you too for some reason. I don't see how that's useful in any cases. What was the actual goal behind, @tohar777?

**Comment by EliteMasterEric** [comment]
This pull request adds poorly-formatted, obvious information to a class which is rarely interacted with (Main.hx's only purpose is to instantiate an FlxGame).

**Pull request closed without merging**
