### PR TITLE
Add Mod Menu

### PR DESCRIPTION
**Pull request by lemz1**
## NOTE
Credit to @JVNpixels for the idea.

Mod icons should be the size of 32x32.

## ADDITIONS
This pr adds a simple mod menu using HaxeUI, which allows you to disable/enable and order mods.
After quitting the mod menu, the assets are reloaded.

## TODO
- [x] Add simple mod menu
- [x] Make mod description popup visible (tooltip)
- [x] Load mods (just steal the code from the old mod menu)
- [x] Save enabled mods and keep the order
- [x] Enabled mod id order needs to be reversed
- [x] Add mod icon to `ModBox`

## KNOWN ISSUES
The game crashes when clicking on `File > Quit`
The crash log is this:
```
Called from haxe.ui.containers.menus.MenuEvents.findRootMenu (haxe/ui/containers/menus/Menu.hx line 374)
Called from haxe.ui.containers.menus.MenuEvents.onItemClick (haxe/ui/containers/menus/Menu.hx line 176)
Called from haxe.ui.util.Timer.delay (haxe/ui/util/Timer.hx line 10)
Called from haxe.ui.backend.TimerImpl.update (haxe/ui/backend/TimerImpl.hx line 17)
Called from openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 402)
Called from openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1399)
Null Object Reference
```

Using the shortcut for quitting (CTRL + Q) works though.

## PREVIEW

https://github.com/user-attachments/assets/2a632cc3-7fb1-4a29-9d88-52c59211cd55

### CODE REVIEW

**Comment by JVNpixels** [comment]
Yea I stopped working on it, but thanks for continuing! Could you give slight credit for the idea?

**Comment by AbnormalPoof** [comment]
Would it be feasible to put mod icons into use in some way for this menu?

**Comment by JVNpixels** [comment]
> Would it be feasible to put mod icons into use in some way for this menu?

Good idea! I was gonna recommend that thought but I got busy.

**Comment by lemz1** [comment]
> Would it be feasible to put mod icons into use in some way for this menu?

I believe HaxeUI got an Image component, so I guess I'll look into it.

**Comment by Cartridge-Man** [comment]
Huh, I actually was about to comment smth like “prob will be added to full game but good try” but oh my god this actually works. Like this looks awesome, keep up the great work

**Comment by Cartridge-Man** [comment]
> Yea I stopped working on it, but thanks for continuing! Could you give slight credit for the idea?

I’m pretty sure the idea to add a mod menu to this game has existed even before Week 7 lol.

**Comment by lightcatdev** [comment]
amazing!

**Comment by AbnormalPoof** [comment]
I've been thinking, would it be possible to also re-order the mods? Perhaps by having arrows on the side of each mod to move them up and down in the mod list.

**Comment by NotHyper-474** [comment]
> I've been thinking, would it be possible to also re-order the mods? Perhaps by having arrows on the side of each mod to move them up and down in the mod list.

In fact it's what is intended: https://github.com/FunkinCrew/Funkin/pull/3029#issuecomment-2232076630
> and players should be able to re-order mods from the UI (similar to how Minecraft displays resource packs).

**Comment by lemz1** [comment]
you can technically reorder the mods by disabling and enabling them, but its kinda annoying to do it like that.

**Pull request closed without merging**
