### PR TITLE
Add an additional dependency for Windows

### PR DESCRIPTION
**Pull request by VMGuy23**

### CODE REVIEW

**Comment by ACardboardBox1** [comment]
Looks good, but you should put it in the "windows only dependencies" section

**Comment by VMGuy23** [comment]
It is

**Review by ACardboardBox1 — APPROVED** [review]
oops i forgot yeah looks good

**Comment by ACrazyTown** [comment]
I swear I never installed Build Tools 2017 and built the game just fine

**Comment by VMGuy23** [comment]
> I swear I never installed Build Tools 2017 and built the game just fine

**Comment by ACardboardBox1** [comment]
> 
> 
> > I swear I never installed Build Tools 2017 and built the game just fine

silence

**Comment by Windows1Door2Daniel** [comment]
ok

**Pull request closed without merging**
