### PR TITLE
Field Read and Write Overloading for Prefereneces

### PR DESCRIPTION
**Pull request by saturn-volv**
This adds an abstracted `PreferenceMap`, which behaves as a StringMap but with some field read and write overloading.

So now instead of needing to call:
```haxe
Save.instance.options.downscroll = true;
```
You can accomplish the same thing with:
```haxe
Preferences.get().downscroll = true;
```

There are other use cases for this but I'm tired and cannot bring myself to list them all right now

### CODE REVIEW

**Review by Raltyro — APPROVED** [review]
Pretty sick
Though i think you can instead immediately do return get().value = value;

**Comment by saturn-volv** [comment]
> return get().value = value;

I initially did but the code style doesn't want inner assignment used.
image

**Comment by Raltyro** [comment]
i forgot codestyle exists whoopsm..

**Comment by EliteMasterEric** [comment]
This looks like a great bit of code cleanup!

Also, the codestyle is bugged, it should be allowing inner assignment in return statements.

**Comment by EliteMasterEric** [comment]
I just looked into this more and I actually don't think this is much of an improvement over the existing `Preferences` map.

**Pull request closed without merging**
