### PR TITLE
[ENHANCEMENT] Stage Editor re-work from the ground up

### PR DESCRIPTION
**Pull request by JustKolosaki**
## Does this PR close any issues? If so, link them below.
N/A
## Briefly describe the issue(s) fixed.
This PR adds a rework/addition of the Stage Editor, nearly identical to the one from the [Stage Editor Engine](https://gamebanana.com/mods/522275), which was also made by me. anysad should be the one with the most familiarity to it, as they have left a suggestion to make it a pull request long time ago.

 In comparison to that iteration, this one is modified to support the Stage Format of the Base Game by implementing z-Index support, changing how the animations are handled and so on.
 
## Include any relevant screenshots or videos.
Welcome Dialog:
screenshot-2024-09-29-19-28-53

Main View:
screenshot-2024-09-29-19-30-47

Some of the Dialogs:
screenshot-2024-09-29-19-38-21

## Note:
If this gets accepted:
1. Haxe-UI Component `.xml` datas for this editor ([link](https://github.com/user-attachments/files/17180202/stage-editor.zip)) would need to be added to `assets/exclude/data/ui`.

2. Stage Files would need to get updated to these ([link](https://github.com/user-attachments/files/17180212/stages.zip)). They are pretty much identical to the current ones, just with the field `directory` added to avoid hard-coding.

3. Pull Request [3397](https://github.com/FunkinCrew/Funkin/pull/3397) would need to get accepted, as this Stage Editor modifies the Stage Data fields that were added in that pr.

### CODE REVIEW

**Comment by ninjamuffin99** [comment]
wow this looks awesome, definitely will be poking into this :)

**Comment by JustKolosaki** [comment]
> wow this looks awesome, definitely will be poking into this :)

My gratitudes :D

**Comment by ninjamuffin99** [comment]
I've rebased your branch to sit on top of `develop` and also made the `assets` submod point towards a `stage-editor` branch in `funkin.assets` repo. Since there's some changes to stage code and whatnot, just poking around and doing testing to see how it shakes out and if there are any bugs we need to fix :)

**Comment by IdealistCat** [comment]
hire this man

**Comment by amyspark-ng** [comment]
incredibly cool

**Comment by JVNpixels** [comment]
This is a really cool upgrade!

**Comment by ninjamuffin99** [comment]
pushed some changes and now i'll merge in, thanks! this is very awesome and I think we'll aim to work off of it!

**Comment by JustKolosaki** [comment]
> pushed some changes and now i'll merge in, thanks! this is very awesome and I think we'll aim to work off of it!

Hell yeah thats awesomesauce thanks cam :]

**Pull request merged**
