### PR TITLE
[BUGFIX] Chart Editor/Gameplay: Fixes countdown and audio artifacts with offsets

### PR DESCRIPTION
**Pull request by Kade-github**
## Does this PR close any issues? If so, link them below.
Don't think anyone uses these so no.
## Briefly describe the issue(s) fixed.
Fixes an issue with offsets that would cause it to mass resync vocals, or go forward in time and back really quickly. Causing a lot of artifacts, lagging the game, and being unpleasant.

This also fixes the song starting before the countdown (due to the offset).
## Include any relevant screenshots or videos.

This shows blammed at +1 second of instrumental offset.

https://github.com/user-attachments/assets/021e5b06-f67c-491a-8e17-d77bddf9c8be
(2nd clip is accidently the normal version of blammed instead of hard, but the point stands)

### CODE REVIEW

**Comment by Kade-github** [comment]
Draft rn as i'm still fixing some weird stuff

**Comment by Kade-github** [comment]
squashed a bunch of commits to make it less spammy on commits

**Comment by Kade-github** [comment]
The last commit was to kind of fix a nasty bug with offsets that causes vocals to be desynced, to fix this i made the tolerance for resyncVocals 5 instead of 100. Didn't seem to affect me that harshly, but it might on lower end devices. I tested on HTML5 and it went well so be aware.

**Comment by Burgerballs** [comment]
i find it funny how my sync fix also fucks with the audio, epic pr tho!

**Pull request merged**
