### PR TITLE
[FEATURE] Restored and fixed Discord RPC support

### PR DESCRIPTION
**Pull request by AltronMaxX**
The title speaks for itself

### CODE REVIEW

**Comment by ninjamuffin99** [comment]
note for future self or eric: 
- if we merge this internally, we need to make sure that it DOESN'T boot up when compiling / testing in debug mode / `-DGITHUB_BUILD` so we don't accidentally have current work being streamed to our discord accounts!

**Comment by AltronMaxX** [comment]
Looks like it not happen in 0.3.3 Xd

**Comment by EliteMasterEric** [comment]
We definitely want to get this into an update at some point (and we'll make sure it involves this PR so you get credited).

**Comment by AltronMaxX** [comment]
Any updates?

**Comment by EliteMasterEric** [comment]
I almost forgot this existed, LOL!

Thanks for updating this today, I will look into merging it

**Comment by EliteMasterEric** [comment]
Another update

This doesn't work, so I'm working on rewriting things myself

**Comment by AltronMaxX** [comment]
:(

**Pull request closed without merging**
