### PR TITLE
fex youre game plxxxxxxsx

### PR DESCRIPTION
**Pull request by i4rfherioeiubjui**
i cum inside mommy meadrtfewdc and shhde likedc it iuwjiedbociwjifk[0oineqpcjrcwn

### CODE REVIEW

**Comment by KitOdin** [comment]
No making pull-requests from kade-engine in the halls!

**Comment by AbnormalPoof** [comment]
@ninjamuffin99 god help us

kid has made 4 fucking pull requests attempting to merge ke into funkin

**Comment by maska228** [comment]
You can already see that god doesn't exist if this kid made 4 prs.

пт, 24 сент. 2021 г. в 03:33, AbnormalPoof ***@***.***>:

> @ninjamuffin99 <https://github.com/ninjamuffin99> god help us
>
> kid has made 4 fucking pull requests attempting to merge ke into funkin
>
>

**Comment by Cheemsandfriends** [comment]
We absolutely need a PR to github to implement a ban system for PR and issues

**Pull request closed without merging**
