### PR TITLE
[BUGFIX] Fixed Song Synchronization

### PR DESCRIPTION
**Pull request by VirtuGuy**
Probably should've explained this when I first made the pull request, but this person explained it well.

image

### CODE REVIEW

**Review by AbnormalPoof — APPROVED** [review]

**Comment by EliteMasterEric** [comment]
What does this actually solve and how?

**Comment by AbnormalPoof** [comment]
> What does this actually solve and how?

This PR addresses an issue with the instrumental being out-of-sync with the vocals when you load a song. Restarting the song properly syncs the vocals and instrumental. PlayState's resyncVocals function is changed to also pause the instrumental in addition to the vocals.

I'm unsure if you are able to reproduce the bug on your end.

Before:

https://github.com/FunkinCrew/Funkin/assets/86753001/e560b8ab-7800-44bf-bb4b-7a5240ca0b00

After:

https://github.com/FunkinCrew/Funkin/assets/86753001/7189d213-53fe-44e2-8598-1787daaf5bca

**Review by cyn0x8 — APPROVED** [review]
desperately needed; its a bit annoying to have to pause/unpause nearly every single time i open a song to fix the desync, especially when testing charting

**Comment by EliteMasterEric** [comment]
Probably going to close this in favor of #3058.

**Pull request closed without merging**
