### PR TITLE
fix focuscamera CLASSIC breaking zooms and snapping

### PR DESCRIPTION
**Pull request by nebulazorua**
When using Classic on FocusCamera, you have to place any zooms AFTER it, because it breaks them. It also snaps the camera, creating for jerky movement when having to use many Classic camera movements
This fixes that behaviour

### CODE REVIEW

**Review by Burgerballs — APPROVED** [review]

**Comment by nebulazorua** [comment]
might update to add "Reset Camera" to the Focus Camera event schema.
You might also want tweens to not reset for fast camera focuses, too, to prevent jerky movements.

**Comment by nebulazorua** [comment]
hopefully should be fixed now

**Review by KutikiPlayz — APPROVED** [review]

**Comment by EliteMasterEric** [comment]
Me and Fabs reviewed this and concluded that the camera zooms work fine without this change. If you want to post the chart you're using and a before/after then that would help with review.

**Comment by nebulazorua** [comment]
> Me and Fabs reviewed this and concluded that the camera zooms work fine without this change. If you want to post the chart you're using and a before/after then that would help with review.

Oh yeah hold on lemme get a video of it
I was running into the issue when porting B-Sides Stress

**Comment by nebulazorua** [comment]
https://github.com/FunkinCrew/Funkin/assets/12458328/2bc0464f-091c-49b8-8af8-9fd7af5514b2

As the camera switching becomes faster, you can see it snap. It looks really bad, imo, and forces me to use an ease style when I'd want to use classic.

**Comment by nebulazorua** [comment]
OH YEAH also fixes a bug with camera zooms and camera focuses, like this (just a test on DadBattle)

Before:
https://github.com/FunkinCrew/Funkin/assets/12458328/df5d0cb9-3726-4d91-baae-f08bbd40f3bd

After:
https://github.com/FunkinCrew/Funkin/assets/12458328/905cbcde-8377-44ca-aca9-57c8e387ea81

**Comment by PurSnake** [comment]
Maybe it's time for a merge?
It was long enough that I didn’t even find it when I made my fix

**Review by PurSnake — APPROVED** [review]

**Review by anysad — APPROVED** [review]
Cocoa Erect camera snapping hurts my brain lol

**Comment by EliteMasterEric** [comment]
Can you update the merge conflicts on this branch? @nebulazorua

**Comment by Hundrec** [comment]
Very good PR, needs to be conflict resolved immediately

**Pull request merged**
