### PR TITLE
Delete source/funkin/graphics/shaders directory

### PR DESCRIPTION
**Pull request by libcorebox**
old opengl 2.1

### CODE REVIEW

**Comment by NotHyper-474** [comment]
? Was this meant for your fork?

**Comment by moxie-coder** [comment]
> old opengl 2.1

https://github.com/user-attachments/assets/8ced2b96-b187-4468-8deb-d3353a97da5d

**Comment by AbnormalPoof** [comment]
??

**Comment by anysad** [comment]
huh

**Comment by libcorebox** [comment]
ala verga todo ni sirvio de nada

**Pull request closed without merging**
