### PR TITLE
seperate nene from abot, and draw abot behind nene

### PR DESCRIPTION
**Pull request by 7oltan**
same as title
doesnt fix any bugs just makes the code cleaner for nene chirstmas and nene dark
(ive been fighting with github for the last ten minutes so sorry if i messed up something)

### CODE REVIEW

**Comment by NotHyper-474** [comment]
Since this only changes the submodule wouldn't it be better to make the PR in the submodule's repository instead?

**Comment by JVNpixels** [comment]
I think you should make this PR in the [funkin.assets](https://github.com/FunkinCrew/funkin.assets) repository, since it seems that there is no actual code being changed here.

**Comment by 7oltan** [comment]
> I think you should make this PR in the [funkin.assets](https://github.com/FunkinCrew/funkin.assets) repository, since it seems that there is no actual code being changed here.

how do i switch

**Comment by AbnormalPoof** [comment]
> > I think you should make this PR in the [funkin.assets](https://github.com/FunkinCrew/funkin.assets) repository, since it seems that there is no actual code being changed here.
> 
> how do i switch

Make a new fork of https://github.com/FunkinCrew/funkin.assets/ with your changes and make a pull request.

**Comment by 7oltan** [comment]
> > > I think you should make this PR in the [funkin.assets](https://github.com/FunkinCrew/funkin.assets) repository, since it seems that there is no actual code being changed here.
> > 
> > 
> > how do i switch
> 
> Make a new fork of https://github.com/FunkinCrew/funkin.assets/ with your changes and make a pull request.

k

**Pull request closed without merging**
