### PR TITLE
Added setup.bat

### PR DESCRIPTION
**Pull request by daPoggers**

### CODE REVIEW

**Review by ThePlank — APPROVED** [review]
350 iq move

**Comment by polybiusproxy** [comment]
> 350 iq move

mf didnt even made the bat
he got it from a gamebanana page

**Comment by ThePlank** [comment]
> > 350 iq move
> 
> mf didnt even made the bat he got it from a gamebanana page

ok i didnt know

**Comment by MrClogsworthYT** [comment]
> > > 350 iq move
> > 
> > 
> > mf didnt even made the bat he got it from a gamebanana page
> 
> ok i didnt know the problem now is that i cant unapprove it

delete the comment

**Comment by ThePlank** [comment]
> > > > 350 iq move
> > > 
> > > 
> > > mf didnt even made the bat he got it from a gamebanana page
> > 
> > 
> > ok i didnt know the problem now is that i cant unapprove it
> 
> delete the comment

you can't delete a comment that is based of a approve

**Comment by MrClogsworthYT** [comment]
> > > > > 350 iq move
> > > > 
> > > > 
> > > > mf didnt even made the bat he got it from a gamebanana page
> > > 
> > > 
> > > ok i didnt know the problem now is that i cant unapprove it
> > 
> > 
> > delete the comment
> 
> you can't delete a comment that is based of a approve

wait what ill try

**Review by MrClogsworthYT — APPROVED** [review]
Deny approval

**Comment by MrClogsworthYT** [comment]
> > > > > 350 iq move
> > > > 
> > > > 
> > > > mf didnt even made the bat he got it from a gamebanana page
> > > 
> > > 
> > > ok i didnt know the problem now is that i cant unapprove it
> > 
> > 
> > delete the comment
> 
> you can't delete a comment that is based of a approve

funk

**Comment by Rudxain** [comment]
Maybe if you say "Deny approval". GitHub has special treatment of text like "fixes #n" (`n` is issue id)

**Comment by MrClogsworthYT** [comment]
Deny approval

**Comment by Rudxain** [comment]
It seems it doesn't work. I found [this link](https://stackoverflow.com/questions/63910871/how-could-i-remove-my-approval-from-a-pull-request-on-github) that kinda helps, but no info about undoing approvals, unfortunately

**Comment by ninjamuffin99** [comment]
i have system that is a bit nicer than setup.bat at least for haxelibs, but I'll keep this one open for the nice VSCommunity setup in-case it might be handy for future use

**Comment by UserUNP** [comment]
~~makefiles~~ ah yes

**Comment by Rudxain** [comment]
What if we use `setup.py` for cross-platform portability? `*.bat` can only be ran on Windows

**Pull request closed without merging**
