### PR TITLE
Show repo size in README.md

### PR DESCRIPTION
**Pull request by Rudxain**
This repo is **VERY THICC** (~0.5GB uncompressed), so it's a good idea to warn anyone who attempts to clone/download it

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Comment by MemeHoovy** [comment]
it's showing the wrong repo

**Comment by Rudxain** [comment]
Oh right, I'm sorry, fixing now..

**Review by MemeHoovy — COMMENTED** [review]
that's better

**Comment by MasterEric** [comment]
This isn't gonna get merged because this repo's too old but I'm gonna make a note to redo the README and slap a bunch of Shields on there

**Pull request closed without merging**
