### PR TITLE
Fixed FunkinSound.hx

### PR DESCRIPTION
**Pull request by embedded-p**
Sheesh, that was a lot of fixing stuff that i accidentally made it a bit broken despite me being unexperienced Haxe programmer, but the HaxeLib itself helped me a lot for dealing with deprecated code lines. Now i know that callback is now OnFrameChange.add and finishCallback is now onFinish.add, which it will come to use later. 

If i did something wrong, let me know, the only thing i don't have a clue about is how is the group named and it's constructed.

>whyyyy, i just wanted to try that compiled dope shit, not to fix everything, i'm not yet ready for that

### CODE REVIEW

**Comment by AbnormalPoof** [comment]
Can you clarify what you actually fixed here?

**Comment by moxie-coder** [comment]
this doesn't really seem like it fixes anything, if anything it only makes it more broken then before

**Comment by embedded-p** [comment]
> this doesn't really seem like it fixes anything, if anything it only makes it more broken then before

Depends, i don't know much about Haxe, i think it's mostly the problem with dependencies.

**Comment by embedded-p** [comment]
> Can you clarify what you actually fixed here?

At the "Files changed" menu, you can see the changes in the code itself, i got rid of the deprecated code/features just because lime complained about that and gave me the options, i got i nearly to be compiled, the only problem is about the new group name/code, and i thought for a moment that i can just ask you for a little help, there's just a teeny-tiny bit of a broken code i pasted from a chatbot because i didn't knew how i do redefine, also i slowly got exhausted, i didn't comprehend the ginormous 
amount of code.

**Comment by Hundrec** [comment]
I'm still unclear on what you fixed here.
Was Lime preventing you from compiling the game using `lime test windows`?
Or was it just a warning about deprecated code?

**Comment by Hundrec** [comment]
Found the warnings OP is fixing in issue #3803 
Deprecated fields don't need to be replaced in order to compile the game. 
You can leave them alone and everything should work fine.

> 46 | FlxG.sound.volumeHandler = function(volume:Float) {
> | ^^^^^^^^^^^^^^^^^^^^^^^^
> | (WDeprecated) volumeHandler is deprecated, use onVolumeChange, instead
> 
> WARNING source/funkin/audio/FunkinSound.hx:465: characters 5-16
> 
> 465 | sound.group = FlxG.sound.defaultSoundGroup;
> | ^^^^^^^^^^^
> | (WDeprecated) sound.group = myGroup is deprecated, use myGroup.add(sound)
> 
> WARNING source/funkin/input/Controls.hx:478: characters 5-29

**Comment by embedded-p** [comment]
> I'm still unclear on what you fixed here. Was Lime preventing you from compiling the game using `lime test windows`? Or was it just a warning about deprecated code?

They were just the warnings

> Found the warnings OP is fixing in issue #3803 Deprecated fields don't need to be replaced in order to compile the game. You can leave them alone and everything should work fine.
> 
> > 46 | FlxG.sound.volumeHandler = function(volume:Float) {
> > | ^^^^^^^^^^^^^^^^^^^^^^^^
> > | (WDeprecated) volumeHandler is deprecated, use onVolumeChange, instead
> > WARNING source/funkin/audio/FunkinSound.hx:465: characters 5-16
> > 465 | sound.group = FlxG.sound.defaultSoundGroup;
> > | ^^^^^^^^^^^
> > | (WDeprecated) sound.group = myGroup is deprecated, use myGroup.add(sound)
> > WARNING source/funkin/input/Controls.hx:478: characters 5-29

I decided to rebuild from scratch, and recently stumbled upon the errors when i typed "lime rebuild windows":

Error: ColorMatrix.cpp
lib/hashlink/src\hl.h(158): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory

Error: JPEG.cpp
lib/hashlink/src\hl.h(158): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory

Error: HarfbuzzBindings.cpp
lib/hashlink/src\hl.h(158): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory

Error: VorbisBindings.cpp
lib/hashlink/src\hl.h(158): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory

Error: GamepadEvent.cpp
lib/hashlink/src\hl.h(158): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory

Error: SDLKeyCode.cpp
C:\Users\user\Documents\funker\Funkin\.haxelib\lime\git\project\lib\sdl\include\SDL_stdinc.h(37): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory

Error: CairoBindings.cpp
lib/freetype/include\config/ftstdlib.h(35): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory

Error: WAV.cpp
lib/hashlink/src\hl.h(158): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory

Error: TextEvent.cpp
lib/hashlink/src\hl.h(158): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory

**Comment by AbnormalPoof** [comment]
> Error: cairo-base64-stream.c
    C:\Users\user\Documents\funker\Funkin.haxelib\lime\git\project\lib\cairo\src\cairoint.h(71): fatal error C1083: Cannot open include file: 'pixman.h': No such file or directory
> Error: cairo-path-bounds.c
    C:\Users\user\Documents\funker\Funkin.haxelib\lime\git\project\lib\cairo\src\cairoint.h(71): fatal error C1083: Cannot open include file: 'pixman.h': No such file or directory

I'm pretty sure this is a weird bug with lime submodules not being initialized properly on hmm.
```zsh
cd .haxelib # Your haxelib folder
cd lime
rm -rf git
git clone https://github.com/FunkinCrew/lime --recursive -b dev-funkin-arm64 git
```

**Comment by embedded-p** [comment]
> > Error: cairo-base64-stream.c
> > C:\Users\user\Documents\funker\Funkin.haxelib\lime\git\project\lib\cairo\src\cairoint.h(71): fatal error C1083: Cannot open include file: 'pixman.h': No such file or directory
> > Error: cairo-path-bounds.c
> > C:\Users\user\Documents\funker\Funkin.haxelib\lime\git\project\lib\cairo\src\cairoint.h(71): fatal error C1083: Cannot open include file: 'pixman.h': No such file or directory
> 
> I'm pretty sure this is a weird bug with lime submodules not being initialized properly on hmm.
> 
> ```shell
> cd .haxelib # Your haxelib folder
> cd lime
> rm -rf git
> git clone https://github.com/FunkinCrew/lime --recursive -b dev-funkin-arm64 git
> ```
> 
> Though you don't need to do this since the FunkinCrew fork already has NDLLs for Windows and macOS. So just run the build command again and it should skip building lime.

May i type those commands? My PC and my Windows system are x64-bit based.

**Comment by NotHyper-474** [comment]
> May i type those commands? I asked for clarity, my PC and my Windows system are x64-bit based.

`lime rebuild` doesn't rebuild the game but instead the libraries (NDLLs) for Lime.

You should use either `lime test` (this one also opens the game) or `lime build` if you want to build the game

**Comment by embedded-p** [comment]
> > May i type those commands? I asked for clarity, my PC and my Windows system are x64-bit based.
> 
> `lime rebuild` doesn't rebuild the game but instead the libraries (NDLLs) for Lime which as AbnormalPoof said is not needed since those already come with Funkin's Lime fork
> 
> You should use either `lime test` (this one also opens the game) or `lime build` if you want to build the game

Now i have enough understanding on compiling FNF, thank you, i may close the pull and change its name.

**Pull request closed without merging**
