### PR TITLE
Chart debug key takes you back to chart editor if you're charting

### PR DESCRIPTION
**Pull request by nebulazorua**
Multiple times I've pressed the chart key while already chart play-testing and lost my chart
This makes it just take you back to the chart editor if you press it while testing

### CODE REVIEW

**Comment by Raltyro** [comment]
fire pull request

**Review by Raltyro — APPROVED** [review]

**Comment by nebulazorua** [comment]
gonna move this into a new branch hold on

**Comment by nebulazorua** [comment]
ehh nvm im fucking LAZY

**Review by EliteMasterEric — APPROVED** [review]
This was really slick and felt good to use! Tested live on stream.

**Comment by Hundrec** [comment]
Changelog Review Note: This belongs in the 0.3.3 milestone

Thanks for this change!

**Pull request merged**
