### PR TITLE
A fucking finder of DanceRight lol instead of a switch xd

### PR DESCRIPTION
**Pull request by Cheemsandfriends**
Hello, So The thing is, It's pretty bad that gf has a lot of protagonism in switch.
I removed her protagonism in that switch lol
(also, I'm lazy to remove the `playanim´ of the switch of characters. of the offset and stuff. you can do it lol

### CODE REVIEW

**Comment by DotWith** [comment]
Would this bug out spooky kids? They don't have hair anims.

**Comment by Cheemsandfriends** [comment]
> 
> 
> Would this bug out spooky kids? They don't have hair anims.

Nop.
Cos the if is like "if the animation isn't starting by hair..."
But I guess it could be even removed for better experience.
Idk xD

**Review by AbnormalPoof — APPROVED** [review]
i need this 

ninjamuffin merge or you're a dumb dumb :D

**Comment by Cheemsandfriends** [comment]
> 
> 
> i need this
> 
> ninjamuffin merge or you're a dumb dumb :D

You can grab my shared code for your mod or thing. I don't think that ninjamuffin will merge but at least I want to give something useful for the fukin master.
I was also going to share the code for the solution of `FlxG.default cameras is deprecated`
But I was told that Cam has already done so what's the point?

**Comment by DotWith** [comment]
Put an `else if` for to play the idle animation.

**Comment by Cheemsandfriends** [comment]
> 
> 
> Put an `else if (blabla I have the idle anim offsets)` for to play the idle animation.

Ok I guess.
 Even tho, It has the thing already but I get what are you talking about

**Comment by DotWith** [comment]
> > 
> 
> > 
> 
> > Put an `else if (blabla I have the idle anim offsets)` for to play the idle animation.
> 
> 
> 
> Ok I guess.
> 
>  Even tho, It has the thing already but I get what are you talking about

For the week7 code you need it because pico-speaker doesn't have an animation

**Comment by DotWith** [comment]
Why remove the playAnim for the characters??

**Comment by Cheemsandfriends** [comment]
> 
> 
> Why remove the playAnim for the characters??

Cos you don't need them anymore lol

**Comment by Cheemsandfriends** [comment]
@DotWith If you want to test the code you can do it.
The code is already tested and always copy pasted for the funkin master I guess

**Comment by DotWith** [comment]
> @DotWith If you want to test the code you can do it.
> 
> The code is already tested and always copy pasted for the funkin master I guess

On phone at school

**Comment by Cheemsandfriends** [comment]
> 
> 
> > @DotWith If you want to test the code you can do it.
> > The code is already tested and always copy pasted for the funkin master I guess
> 
> On phone at school

Oh xd

**Pull request closed without merging**
