### PR TITLE
Cool Things

### PR DESCRIPTION
**Pull request by Gidk-g**
polymod shits

### CODE REVIEW

**Comment by MemeHoovy** [comment]
not bad, but MasterEric is making a better system though

**Review by MemeHoovy — CHANGES_REQUESTED** [review]
not bad, but MasterEric is making a better system though

**Comment by Gidk-g** [comment]
> not bad, but MasterEric is making a better system though

true

**Comment by Gidk-g** [comment]
goofy ahhhh

**Pull request closed without merging**
