### PR TITLE
Completely un-hardcode songs, various fixes and improvements

### PR DESCRIPTION
**Pull request by Enovale**
Apologies for not splitting this shit into a bunch of smaller pull requests, it ended up being much more ambitious than I originally planned.

So basically I redid the way songs are loaded so that a song's music, json, and metadata are all stored in a self contained folder, and all songs are dynamically loaded from "songs/". What this means is you can now create your own song, put it into the files, and play it in Freeplay without rebuilding the game.

Along with this I also made it so the story mode is loaded dynamically from a JSON, so the end user could even make their own campaign using their own custom songs, and it makes creating more story mode weeks easier on the developer side. 

I also made sure that official songs are included in the assets on web platforms because HTML5/Flash do not have filesystem support.

The problem is that merging this is gonna take more work than just pressing the github merge button. I changed a lot of shit here and not everything is perfect. The most notable is that the story mode screen doesnt show the week names properly, and it looks like shit. That's because you originally used hard coded sprites for the week names, and your Alphabet class/art doesn't have bold numbers in it.

I wanna see this game become the Clone Hero of Newgrounds, and to do that i'll need some help from you guys to merge this pull request. Thank you.

Lemme know if you need my help, have questions, whatever :P

### CODE REVIEW

**Comment by ninjamuffin99** [comment]
got a good chunk of changes, finished up week 3 update, so gonna dig thru this rn

**Comment by ElijahZAwesome** [comment]
I can make changes or whatever if somethin doesnt fit your style or you can't figure out something. I didn't comment much of my code, sorry

**Comment by Mar10Josh** [comment]
So where is songs/

**Comment by ElijahZAwesome** [comment]
Theres a "bug" (I intended it at the time but kinda regret it) where it wont copy the songs folder to the output build because i dont want to have to compile all the songs if you're on desktop. Just copy the songs/ folder from the source tree to your output build next to the main binary

**Comment by ElijahZAwesome** [comment]
Any updates on this?

**Comment by ninjamuffin99** [comment]
still gotta peep thru this! and will! just got week 4 update, so gonna spend the next little while to update programming backend stuff

**Comment by Coolguy3289** [comment]
Was this still considered to be merged @ninjamuffin99 or has it been implemented in another way at this point?

**Pull request closed without merging**
