### PR TITLE
[CLEANUP] Softcode Tutorial HEY! events from code to JSON

### PR DESCRIPTION
**Pull request by anysad**
## Briefly describe the issue(s) fixed.
* As the title suggests, moves the hardcoded `HEY!` events in Tutorial to already established (aka normal) events in the game. After all, why do we need `danceOnBeat()` called every single beat just for these 4 events?

### CODE REVIEW

**Comment by moxie-coder** [comment]
you need to redo your branch with the develop branch

**Comment by EliteMasterEric** [comment]
The `main` branch had some documentation changes that `develop` didn't, just fixed it now.

**Comment by EliteMasterEric** [comment]
approved

**Comment by biomseed** [comment]
week 8 gonna be crazy with all these fixes

**Pull request merged**
