### PR TITLE
[ENHANCEMENT] Custom Popups and Countdowns

### PR DESCRIPTION
**Pull request by anysad**
## Briefly describe the issue(s) fixed.
- This PR aims to give players the ability to have custom popups and countdown graphics/sounds. Currently, some of the assets were moved into their own folders, so that the player has an easy way of navigating and finding them.
- By using this new ability, modders FINALLY have the option to have their own assets for popups and countdowns. `(see video below)`
- This PR fixes the countdown assets having random sizes, depending on their stage. **(the scaling of normal assets were based on pixel countdown assets)** `(see video below)`
- ~~This PR fixes the `Song Metadata` box in the chart editor, letting you finally choose notestyles easily. `(see photo below)`~~ Moved to https://github.com/FunkinCrew/funkin.assets/pull/54
## Include any relevant screenshots or videos.
- `twinsomnia`  notestyle **(no assets)** / `twinsomnia-booger` notestyle **(with assets)**

https://github.com/user-attachments/assets/17f22704-2405-4390-b5d5-0b3f61cfaccf

- Fixed countdown assets size:

https://github.com/user-attachments/assets/5719d131-2538-40af-b689-932df46521c0

### CODE REVIEW

**Comment by Hundrec** [comment]
Cool stuff anysad!

**Review by Hundrec — APPROVED** [review]

**Review by JVNpixels — APPROVED** [review]

**Comment by anysad** [comment]
> Cool stuff anysad!

thank you, mister Hundrec 🫡

**Comment by anysad** [comment]
just saw that I accidentally made a copy of the `hand_textbox` texture, whoops. will fix it a little later

**Comment by EliteMasterEric** [comment]
Might review this and rework it myself later, but the way I originally architected this system, the plan was that custom popups and countdowns would be defined by the current note style.

**Comment by anysad** [comment]
> the plan was that custom popups and countdowns would be defined by the current note style

Your wish is my command. Starting to work on it.

**Comment by anysad** [comment]
@EliteMasterEric I made it use the current note style, and if no assets were found for the specific note style, it reverts back to using the default assets. `(funkin/pixel based if the note style is pixel or not)`

**Review by JVNpixels — CHANGES_REQUESTED** [review]
You could center the countdown to make it look cleaner, besides that this PR deserves to be merged!

**Comment by EliteMasterEric** [comment]
> @EliteMasterEric I made it use the current note style, and if no assets were found for the specific note style, it reverts back to using the default assets. `(funkin/pixel based if the note style is pixel or not)`

Each note style defines a fallback note style, all assets should check if the specific note style has an asset, then check if the fallback has it, then check if ITS fallback has it, continuing until you reach a note style with no fallback. The default `funkin` note style should have every asset defined.

**Comment by anysad** [comment]
yes eric

**Comment by anysad** [comment]
@EliteMasterEric Done.

- Countdown (`twinsomnia-booger`/`twinsomnia`/`funkin`)

https://github.com/user-attachments/assets/d3ff7992-7000-4c6c-975a-65de32737941

- Countdown (`twinsomnia-booger`/`twinsomnia`/`funkin`) (**no exact order**)

https://github.com/user-attachments/assets/20783801-69fc-4974-a60f-c6965a762761

**Comment by anysad** [comment]
Manipulating a little bit with assets (removed the `0`, and it will use `funkin` since there is no fallback)

https://github.com/user-attachments/assets/a86baa8d-f470-451e-b245-df1276ff4825

**Comment by anysad** [comment]
Also, will have to cleanup the code tomorrow a little to remove the unnecessary `fetchNoteStyle()` calls

**Comment by anysad** [comment]
> You could center the countdown to make it look cleaner, besides that this PR deserves to be merged!

As you suggested, I centered it.

**Review by JVNpixels — APPROVED** [review]
PR 100% Merge deserved

**Review by Cartridge-Man — APPROVED** [review]
This is gonna be so helpful if this gets merged ngl

**Comment by EliteMasterEric** [comment]
This code looks great overall and seems to not break anything.

There are some tweaks I want to make (for example, there are a lot of merge conflicts with our internal branch) but I will make those changes myself.

**Pull request merged**
