### PR TITLE
Fix compilation issues

### PR DESCRIPTION
**Pull request by Stilic**
Fixes an issue where you couldn't compile the game at all.
Also allows the game to be built on Linux again.

### CODE REVIEW

**Comment by AbnormalPoof** [comment]
Mostly a duplicate of #3438 aside from the hmm.json change

**Comment by Stilic** [comment]
> Mostly a duplicate of #3438 aside from the hmm.json change

It's needed to allow the game to compile on Linux, at least in my case.

**Comment by AbnormalPoof** [comment]
Fair enough.

**Comment by Stilic** [comment]
Just noticed #3438 was merged.
I'm closing this and make a new PR with the fix for Linux compilation.

**Comment by Stilic** [comment]
New PR opened: #3454.

**Pull request closed without merging**
