### PR TITLE
`(TitleState.hx, swagShader variable)` Just a little null check

### PR DESCRIPTION
**Pull request by Wither362**
Yep, that’s it. A null check just for no crash when pressing left or right arrow.

### CODE REVIEW

**Review by MemeHovy — APPROVED** [review]

**Comment by ACrazyTown** [comment]
I don't think they will accept PRs. This source is like a year old lol

**Comment by ShadowMilky** [comment]
> I don't think they will accept PRs. This source is like a year old lol

they updated the repo to contain the week 7 source anyway tho

**Review by ShadowMilky — APPROVED** [review]

**Comment by mitaka78** [comment]
> > I don't think they will accept PRs. This source is like a year old lol
> 
> they updated the repo to contain the week 7 source anyway tho

That's because people wanted to see the Week 7 source code, it's not a sign that this repository is up to date or accepting PRs.

**Comment by Wither362** [comment]
> > > I don't think they will accept PRs. This source is like a year old lol
> > 
> > 
> > they updated the repo to contain the week 7 source anyway tho
> 
> That's because people wanted to see the Week 7 source code, it's not a sign that this repository is up to date or accepting PRs.

Thanks for the **support**.

**Pull request closed without merging**
