### PR TITLE
[ENHANCEMENT/RECOVERY]: Mods Menu

### PR DESCRIPTION
**Pull request by JVNpixels**
# !!!This PR is a DRAFT / W.I.P!!! 
## There are lots of steps left, like changing the directory to read it in, make it use the official FNF alphabet font, and etc.
**This Pull Request adds the scrapped mods menu back, and makes it alot cleaner.**

### CODE REVIEW

**Comment by JVNpixels** [comment]
Some changes will be coming soon! I will be adding checkboxes, but I am going to eat pasta now.

**Comment by JVNpixels** [comment]
Camera is glitched, and needs fixing

**Comment by anysad** [comment]
Are you going to make it similar to Psych Engine, or will you go with a different approach?

**Comment by JVNpixels** [comment]
diff approach, i’ve been feeling kinda tired these last couple of days

**Comment by EliteMasterEric** [comment]
Does this just reimplement the old menu that Cam showed on stream one time?

That menu is fundamentally inadequate to what the game needs for mods; mods have an enabled/disabled status as well as strict order, and players should be able to re-order mods from the UI (similar to how Minecraft displays resource packs).

**Comment by JVNpixels** [comment]
yea it re adds it back, but its improved and still wip

**Comment by JVNpixels** [comment]
you can reorder mods using “i” and “k”

**Pull request closed without merging**
