### PR TITLE
custom variations in freeplay

### PR DESCRIPTION
**Pull request by nebulazorua**
variations in freeplay yeah
havent found any issues from veerrryy basic testing

### CODE REVIEW

**Review by Raltyro — APPROVED** [review]

**Comment by EliteMasterEric** [comment]
Reviewing the code I'm fairly certain this will break things in some circumstances, I will have to review and possibly rework things.

**Comment by nebulazorua** [comment]
> Reviewing the code I'm fairly certain this will break things in some circumstances, I will have to review and possibly rework things.

yeah I haven't done much testing on it and it'll prob break stuff knowing me, but hopefully it'll be a half-decent start for someone better than me to do smth

**Comment by amyspark-ng** [comment]
what does this do?

**Comment by nebulazorua** [comment]
> what does this do?

allows you to use custom variations difficulties in freeplay

**Comment by nebulazorua** [comment]
Closing this as I don't feel like updating this for 0.4.0+

**Pull request closed without merging**
