### PR TITLE
Fix week7 source code errors（I can't fix stress's cut animation）

### PR DESCRIPTION
**Pull request by salumod**
Music from dialogueBox.hx is not allowed to play after entering PlayState from freeplay

### CODE REVIEW

**Comment by MemeHovy** [comment]
what the absolute hell happened to that commit @salumod

**Comment by salumod** [comment]
> what the absolute hell happened to that commit @salumod

I didn't clone the updated library, so the updated thing is attached to the source code of v0.2.7

**Comment by salumod** [comment]
But it's not a big problem. Just download the source code

**Comment by salumod** [comment]
https://github.com/FunkinCrew/Funkin/pull/2124

**Pull request closed without merging**
